# Generated by Django 3.2.7 on 2021-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidade', models.CharField(max_length=150)),
                ('edad', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
