# Generated by Django 3.2.7 on 2021-09-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='apellidade',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='student',
            name='edad',
        ),
    ]
