# Generated by Django 3.2.7 on 2021-09-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_auto_20210921_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
